# controller node interfaces
export CH_M_INTERFACE="eno1"
export CH_M_INTERFACE_ADDRESS="210.125.84.61"
export CH_C_INTERFACE_ADDRESS="172.25.0.51"
export CH_D_INTERFACE_ADDRESS="10.0.0.1"

# Compute node interfaces
export COMPUTE_NODE_CH_M_INTERFACE="eno1"
export COMPUTE_NODE_CH_M_INTERFACE_ADDRESS="210.125.84.62"
export COMPUTE_NODE_CH_C_INTERFACE_ADDRESS="172.25.0.52"
export COMPUTE_NODE_CH_D_INTERFACE_ADDRESS="10.0.0.2"

# Region : Usually matters when Tricircle is used
export REGION_NAME="RegionOne"

export MYSQL_ROOT_PASSWORD="fn"
export RABBITMQ_PASSWORD="fn"

export KEYSTONE_DB_PASSWORD="fn"
export GLANCE_DB_PASSWORD="fn"
export NOVA_DB_PASSWORD="fn"
export NEUTRON_DB_PASSWORD="fn"

export OPENSTACK_GLANCE_USER_PASSWORD="fn"
export OPENSTACK_NOVA_USER_PASSWORD="fn"
export OPENSTACK_PLACEMENT_USER_PASSWORD="fn"
export OPENSTACK_NEUTRON_USER_PASSWORD="fn"

export OPENSTACK_ADMIN_USER_PASSWORD="fn"
export OPENSTACK_DEMO_USER_PASSWORD="fn"

