# Controller node interfaces
export CH_M_INTERFACE="eno1"
export CH_M_INTERFACE_ADDRESS="210.125.84.226"
export CH_C_INTERFACE_ADDRESS="172.20.91.226"
export CH_D_INTERFACE_ADDRESS="172.30.91.226"

# Compute node interfaces
export COMPUTE_NODE_CH_M_INTERFACE="eno1"
export COMPUTE_NODE_CH_M_INTERFACE_ADDRESS="210.125.84.228"
export COMPUTE_NODE_CH_C_INTERFACE_ADDRESS="172.20.91.228"
export COMPUTE_NODE_CH_D_INTERFACE_ADDRESS="172.30.91.228"

# Region : Usually matters when Tricircle is used
export REGION_NAME="RegionTwo"

export MYSQL_ROOT_PASSWORD="H7skyk7PTY3eLQnS"
export RABBITMQ_PASSWORD="HdP5NELjPL5rcYyZ"

export KEYSTONE_DB_PASSWORD="d6sEaF3qfx3GBN4s"
export GLANCE_DB_PASSWORD="8Rc2XjEne4mP5J7x"
export NOVA_DB_PASSWORD="urU6bELGH5ryv9Nv"
export NEUTRON_DB_PASSWORD="YvLWwm4RG7J9wX8u"

export OPENSTACK_GLANCE_USER_PASSWORD="4pkheU4s4j8napMX"
export OPENSTACK_NOVA_USER_PASSWORD="ZXEvQCBZrJQKzA5d"
export OPENSTACK_PLACEMENT_USER_PASSWORD="v4v6wDWdbGuuRwXQ"
export OPENSTACK_NEUTRON_USER_PASSWORD="QYDH9WHcz22brN6U"

export OPENSTACK_ADMIN_USER_PASSWORD="z52Dbg8pDbtWVPtX"
export OPENSTACK_DEMO_USER_PASSWORD="9wnK53NZHXnKpxFq"
